apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-ticker
  namespace: stocks
  labels:
    app: stock-ticker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-ticker
  template:
    metadata:
      labels:
        app: stock-ticker
    spec:
      containers:
      - name: stock-ticker
        image: stock-ticker:latest
        imagePullPolicy: Never # just for minikube run or else it will pull from docker registry
        env:
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: secret
                key: apiKey
                optional: false
          - name: SYMBOL
            valueFrom:
              configMapKeyRef:
                name: config
                key: symbol
          - name: NDAYS
            valueFrom:
              configMapKeyRef:
                name: config
                key: nDays
          - name: REDIS_URL
            valueFrom:
              configMapKeyRef:
                name: config
                key: redisURL
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: stock-ticker
spec:
  type: NodePort
  selector:
    app: stock-ticker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

