version: '3'

services:
  stock-ticker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      REDIS_URL: redis:6379
#    networks: # Networks to join (Services on the same network can communicate with each other using their name)
#      - backend

  # Redis Service
  redis:
    image: "redislabs/rejson:latest"
    restart: unless-stopped
    expose:
      - "6379"
    ports:
      - "6379:6379"
#    networks:
#      - backend
#
#networks:
#  backend: